"""Create DB

Revision ID: d6f3a00ef342
Revises: 
Create Date: 2025-07-01 13:39:34.241140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f3a00ef342'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav_items',
    sa.Column('nav_item_id', sa.Integer(), nullable=False),
    sa.Column('nav_item_label', sa.String(length=50), nullable=False),
    sa.Column('nav_item_to', sa.String(length=100), nullable=False),
    sa.Column('nav_item_section', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('nav_item_id')
    )
    op.create_index(op.f('ix_nav_items_nav_item_id'), 'nav_items', ['nav_item_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=50), nullable=False),
    sa.Column('project_description', sa.String(length=100), nullable=False),
    sa.Column('project_img', sa.String(length=100), nullable=False),
    sa.Column('project_category', sa.String(length=255), nullable=False),
    sa.Column('project_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('project_img'),
    sa.UniqueConstraint('project_title')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_title', sa.String(length=50), nullable=False),
    sa.Column('service_price', sa.String(length=50), nullable=False),
    sa.Column('service_description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_index(op.f('ix_services_service_id'), 'services', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_service_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_nav_items_nav_item_id'), table_name='nav_items')
    op.drop_table('nav_items')
    # ### end Alembic commands ###
